variable "aws-region" {}
variable "amis" {}
variable "aws-instance-type" {}
variable "keypair-name" {}
variable "vpc-cidr" {}
variable "public-subnet" {}
variable "private-subnet" {}
variable "name" {}
variable "jenkins_url" {}
variable "jenkins_username" {}
variable "jenkins_password" {}
variable "jenkins_slave_nb_executor" {}
variable "jenkins_slave_home" {}
variable "jenkins_slave_user" {}
variable "jenkins_slave_group" {}